apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lab3
  name: hostpath-pvc
spec:
 resources:
  requests:
      storage: 1Gi
 accessModes:
  - ReadWriteOnce
 storageClassName: localstorage
