apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: lab3
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
  hostpath:
    path: /logs/files
